/**
 * Default English copy for the app.
 * Future locales should mirror this shape.
 */
export const enStrings = {
  app: {
    brandName: 'Linghuist',
  },
  auth: {
    metaTitle: 'Linghuist - Join the Pulse',
    metaDescription: 'Join Linghuist and learn languages through real conversation.',
    help: 'Help',
    heroTitleLead: 'Unlock the world through',
    heroTitleHighlight: 'genuine conversation',
    heroSubtitle: 'Skip the flashcards. Join the digital lounge where language is lived, not just studied.',
    formWelcomeTitle: 'Welcome Back!',
    formWelcomeSubtitle: 'Step into the kinetic midnight of language learning.',
    formWelcomeTitleSignup: 'Join The Lounge!',
    formWelcomeSubtitleSignup: 'Create an account and start living the language tonight.',
    forgotTitle: 'Reset your password',
    forgotSubtitle: 'Enter your email address. If an account exists, we will send you a link to choose a new password.',
    forgotSubmit: 'Send reset link',
    forgotSending: 'Sending…',
    backToSignIn: 'Back to sign in',
    tabLogin: 'Log In',
    tabSignUp: 'Sign Up',
    labelEmail: 'E-Mail Address',
    labelPassword: 'Password',
    labelConfirmPassword: 'Confirm Password',
    emailPlaceholder: 'name@company.com',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'Forgot?',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    orContinueWith: 'OR CONTINUE WITH',
    continueWithGoogle: 'Google',
    continueWithGitHub: 'GitHub',
    footerAgreementLead: 'By joining, you agree to our',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    footerAgreementEnd: '.',
    pwaTitle: 'Download Linghuist',
    pwaSubtitle: 'The lounge is open 24/7 on iOS & Android.',
    pwaInstall: 'Install',
    bottomNavLogin: 'Log In',
    bottomNavSignup: 'Sign Up',
    passwordRulesHint: 'At least 8 characters, including one uppercase letter and one special character.',
    errorPasswordMismatch: 'Passwords do not match.',
    errorUnexpected: 'Something went wrong. Please try again.',
    errorServerNotConfigured: 'Server URL is not configured for this app.',
    signingIn: 'Signing In…',
    creatingAccount: 'Creating Account…',
    toastInvalidCredentials: 'Check your email and password and try again.',
    toastEmailVerificationSent: 'Verification email sent. Check your inbox to confirm your account.',
    toastPasswordResetSent: 'If an account exists for that email, we sent a password reset link. Check your inbox.',
    validationEmailInvalid: 'Enter a valid email address.',
    validationPasswordRequired: 'Password is required.',
    validationPasswordSignup: 'Password must contain 1 uppercase and 1 special character (minimum 8 characters).',
    validationConfirmPasswordRequired: 'Confirm your password.',
    validationConfirmPasswordMatch: 'Passwords must match.',
  },
  community: {
    pageTitle: 'Community',
    pageDescription: 'Discover language partners and start practicing.',
    discoverTitle: 'Discover Partners',
    discoverSubtitle: 'Find language partners and start practicing.',
    filterButton: 'Filters',
    filterModalTitle: 'Filters',
    filterApply: 'Apply',
    filterCancel: 'Cancel',
    resetFilters: 'Reset Filters',
    filterKnownAll: 'Known: All',
    filterLearningAll: 'Learning: All',
    filterCountryAll: 'Country: All',
    placeholderKnown: 'Known language',
    placeholderLearning: 'Learning language',
    placeholderCountry: 'Country',
    placeholderUsernameSearch: 'Search by username',
    labelAgeRange: 'Age',
    languageUnknown: 'Unknown language',
    labelNative: 'Native',
    labelLearning: 'Learning',
    loadingUsers: 'Loading users...',
    loadingMoreUsers: 'Loading more users...',
    noUsers: 'No users found.',
    navCommunity: 'Community',
    navFeed: 'Feed',
    navChats: 'Chats',
    navNotifications: 'Notifications',
    navProfile: 'Profile',
    navProfileMenu: 'Account menu',
    navMenuProfile: 'Profile',
    navMenuLogOut: 'Log out',
  },
} as const;
