/**
 * Default English copy for the app.
 * Future locales should mirror this shape.
 */
export const enStrings = {
  app: {
    brandName: 'Linghuist',
  },
  auth: {
    metaTitle: 'Linghuist - Join the Pulse',
    metaDescription: 'Join Linghuist and learn languages through real conversation.',
    help: 'Help',
    heroTitleLead: 'Unlock the world through',
    heroTitleHighlight: 'genuine conversation',
    heroSubtitle: 'Skip the flashcards. Join the digital lounge where language is lived, not just studied.',
    formWelcomeTitle: 'Welcome Back!',
    formWelcomeSubtitle: 'Step into the kinetic midnight of language learning.',
    formWelcomeTitleSignup: 'Join The Lounge!',
    formWelcomeSubtitleSignup: 'Create an account and start living the language tonight.',
    forgotTitle: 'Reset your password',
    forgotSubtitle: 'Enter your email address. If an account exists, we will send you a link to choose a new password.',
    forgotSubmit: 'Send reset link',
    forgotSending: 'Sending…',
    backToSignIn: 'Back to sign in',
    tabLogin: 'Log In',
    tabSignUp: 'Sign Up',
    labelEmail: 'E-Mail Address',
    labelPassword: 'Password',
    labelConfirmPassword: 'Confirm Password',
    emailPlaceholder: 'name@company.com',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'Forgot?',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    orContinueWith: 'OR CONTINUE WITH',
    continueWithGoogle: 'Google',
    continueWithGitHub: 'GitHub',
    footerAgreementLead: 'By joining, you agree to our',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    footerAgreementEnd: '.',
    pwaTitle: 'Download Linghuist',
    pwaSubtitle: 'The lounge is open 24/7 on iOS & Android.',
    pwaInstall: 'Install',
    bottomNavLogin: 'Log In',
    bottomNavSignup: 'Sign Up',
    passwordRulesHint: 'At least 8 characters, including one uppercase letter and one special character.',
    errorPasswordMismatch: 'Passwords do not match.',
    errorUnexpected: 'Something went wrong. Please try again.',
    errorServerNotConfigured: 'Server URL is not configured for this app.',
    signingIn: 'Signing In…',
    creatingAccount: 'Creating Account…',
    toastInvalidCredentials: 'Check your email and password and try again.',
    toastEmailVerificationSent: 'Verification email sent. Check your inbox to confirm your account.',
    toastPasswordResetSent: 'If an account exists for that email, we sent a password reset link. Check your inbox.',
    validationEmailInvalid: 'Enter a valid email address.',
    validationPasswordRequired: 'Password is required.',
    validationPasswordSignup: 'Password must contain 1 uppercase and 1 special character (minimum 8 characters).',
    validationConfirmPasswordRequired: 'Confirm your password.',
    validationConfirmPasswordMatch: 'Passwords must match.',
  },
  community: {
    pageTitle: 'Community',
    pageDescription: 'Discover language partners and start practicing.',
    discoverTitle: 'Discover Partners',
    discoverSubtitle: 'Find language partners and start practicing.',
    filterButton: 'Filters',
    filterModalTitle: 'Filters',
    filterApply: 'Apply',
    filterCancel: 'Cancel',
    resetFilters: 'Reset Filters',
    filterKnownAll: 'Known: All',
    filterLearningAll: 'Learning: All',
    filterCountryAll: 'Country: All',
    placeholderKnown: 'Known language',
    placeholderLearning: 'Learning language',
    placeholderCountry: 'Country',
    placeholderUsernameSearch: 'Search by username',
    labelAgeRange: 'Age',
    languageUnknown: 'Unknown language',
    labelNative: 'Native',
    labelLearning: 'Learning',
    loadingUsers: 'Loading users...',
    loadingMoreUsers: 'Loading more users...',
    noUsers: 'No users found.',
    navCommunity: 'Community',
    navFeed: 'Feed',
    navChats: 'Chats',
    navNotifications: 'Notifications',
    navProfile: 'Profile',
    navProfileMenu: 'Account menu',
    navMenuProfile: 'Profile',
    navMenuLogOut: 'Log out',
  },
  profile: {
    pageTitle: 'Profile',
    pageDescription: 'Update your profile and language preferences.',
    loadError: 'Failed to load profile.',
    saveSuccess: 'Profile updated successfully.',
    saveError: 'Failed to update profile.',
    avatarUploadSuccess: 'Profile picture updated successfully.',
    avatarUploadError: 'Failed to upload profile picture.',
    createFirstPost: 'Create Your First Post',
    noPostsTitle: 'No posts yet',
    noPostsSubtitle: 'Share your progress with the community.',
    editBio: 'Edit Bio',
    edit: 'Edit',
    viewPublicProfile: 'View Public Profile',
    saveProfileChanges: 'Save Profile Changes',
    sectionMyPosts: 'My Posts',
    sectionLanguageMastery: 'Language Mastery',
    sectionAccountCredentials: 'Account Credentials',
    sectionNativeFluent: 'Native Languages',
    sectionCurrentlyLearning: 'Currently Learning',
    sectionSecurityAccess: 'Security & Access',
    sectionSecuritySubtitle: 'Manage your restrictions and session data.',
    manageBlockList: 'Blocked Users',
    deleteAccount: 'Delete Account',
    deleteAccountConfirmTitle: 'Delete account?',
    deleteAccountConfirmBody: 'Enter your password to permanently delete your account.',
    deleteAccountPasswordLabel: 'Password',
    deleteAccountConfirmAction: 'Delete',
    deleteAccountAdminBlocked: 'Admin accounts cannot be deleted from this screen.',
    deleteAccountSuccess: 'Account deleted successfully.',
    deleteAccountError: 'Failed to delete account.',
    blockListComingSoon: 'Block list management is coming soon.',
    createPostComingSoon: 'Post composer is coming soon.',
    bioTooLong: 'Bio cannot exceed 300 characters.',
    currentCountry: 'Current Country',
    age: 'Age',
    editAge: 'Edit Age',
    emailAddress: 'Email Address',
    languageModalTitle: 'Edit Languages',
    languageModalSubtitle: 'Select language and level for each entry.',
    languageLabel: 'Language',
    levelLabel: 'Level',
    addLanguage: 'Add Language',
    removeLanguage: 'Remove',
    cancel: 'Cancel',
    apply: 'Apply',
    chooseLanguage: 'Choose language',
    chooseLevel: 'Choose level',
    levelNative: 'Native',
    levelFluent: 'Fluent',
    levelIntermediate: 'Intermediate',
    levelBeginner: 'Beginner',
    levelAdvanced: 'Advanced',
    unknownLanguage: 'Unknown language',
    profileHeadingFallback: 'User',
    profileImageMenu: 'Profile image menu',
    uploadProfilePicture: 'Upload profile picture',
    viewProfileImage: 'View profile image',
    closeImagePreview: 'Close image preview',
    updateLocation: 'Update',
    updatingLocation: 'Updating...',
    locationUpdated: 'Location updated.',
    locationUnsupported: 'Location is not supported on this device.',
    locationResolveError: 'Could not detect your location.',
    countryNotSet: 'Not set',
    minNativeLanguageRequired: 'At least one native language is required.',
    minLearningLanguageRequired: 'At least one learning language is required.',
    loadingProfile: 'Loading profile',
    bioFallback: 'No bio yet.',
    friendsSectionTitle: 'Friends',
    friendsTabFriends: 'Friends',
    friendsTabIncoming: 'Incoming',
    friendsTabSent: 'Sent',
    noFriends: 'No friends yet',
    incomingRequests: 'Incoming Requests',
    outgoingRequests: 'Outgoing Requests',
    noIncomingRequests: 'No incoming requests',
    noOutgoingRequests: 'No outgoing requests',
    pending: 'Pending',
    accept: 'Accept',
    reject: 'Reject',
    cropAvatarTitle: 'Crop Avatar',
    sectionPosts: 'Posts',
    noPostsSimple: 'No posts',
    profileAccessDenied: 'You do not have access to this profile.',
    signInToViewProfile: 'Sign in to view this profile.',
    addFriend: 'Add friend',
    sentRequest: 'Request sent',
    requestReceived: 'Request received',
    removeFriend: 'Remove friend',
    chatNow: 'Chat',
    blockUser: 'Block user',
    confirmRemoveFriendTitle: 'Remove friend?',
    confirmRemoveFriendBody: 'You will no longer be connected as friends.',
    confirmBlockTitle: 'Block this user?',
    confirmBlockBody: 'They will not be able to interact with you. You can manage blocked users from your profile settings.',
    friendRequestSent: 'Friend request sent.',
    friendRemoved: 'Friend removed.',
    userBlocked: 'User blocked.',
    socialActionError: 'Something went wrong. Please try again.',
    ageLabelShort: 'y.o.',
  },
} as const;
